version: "3.8"

services:
#  webtice-server:
#    container_name: webtice-server
#    build:
#      context: ./backend
#      dockerfile: Dockerfile
#    image: webtice-server
#    ports:
#      - "8080:8080"
#    depends_on:
#      - webticedb
#    restart: always
#
#  webtice-tg-bot:
#    build:
#      context: ./telegram-bot
#      dockerfile: Dockerfile
#    container_name: webtice-tg-bot
#    environment:
#      TELEGRAM_BOT_TOKEN: ${TELEGRAM_BOT_TOKEN}
#      ADMINS_CHAT_IDS: ${ADMINS_CHAT_IDS}
#      DATABASE_NAME: ${DATABASE_NAME}
#      DATABASE_HOST: ${DATABASE_HOST}
#      DATABASE_USER: ${DATABASE_USER}
#      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
#    command: python3 main.py
#    depends_on:
#      - webticedb
#    restart: always

  webticedb:
    image: postgres:12
    volumes:
      - webtice-app-db-data:/var/lib/postgresql/data/pgdata
    ports:
      - '5432:5432'
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
  
volumes:
  webtice-app-db-data:
